# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ed87b154a8be677090357ae4f29cc0db7e8dcd552d8d620be7fc57169676ade2a92597f77b6e6792f0984e88f9705b189feac041673168395fe43ef2b691eea

test:
  secret_key_base: 0cf8dace633c99b651233f1d755832b090be62acdcec9de523e10fee1b077ba7ac2138caf5b0b01a6cce892af31a762248562e274e4e55034cf33059d7196cab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
